name: hello_dart_action
description: A hello world GitHub Action written in Dart.
version: 0.0.0
#homepage: https://www.example.com

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  js: ^0.6.3-nullsafety.3

dev_dependencies:
  build_runner: ^1.10.0
  build_web_compilers: ^2.11.0
  pedantic: ^1.9.0
